positions:
  filename: /mnt/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "docker-logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "docker"
          __path__: /logs/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            message: message
      - timestamp:
          source: timestamp
          format: RFC3339

